---
title: "Fix the variables"
labels: "Testing some shit"

body:
  - type: markdown
    attributes:
      value: "# TESTING SOME SHIT"
  - type: markdown
    attributes:
      value: |
        Use this form to fill in variables.
  - type: input
    id: a0-param
    attributes:
      label: "What is a0?"
      description: "Enter a0."
      placeholder: "0.30"
    validations:  
      required: true
  - type: input
    id: k-param
    attributes:
      label: "What is k?"
      description: "k = what?"
      placeholder: "500"
    validations:  
      required: true
  - type: input
    id: tau-param
    attributes:
      label: "What is tau?"
      description: "tau = what?"
      placeholder: "0.20"
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: checkboxes
    id: which-group
    attributes:
      label: "For which working group(s) are you providing this workstream update?"
      options:
        - label: Coordination & Admin
        - label: Metadata Standards
        - label: Ecosystem Mapping
        - label: Partnerships
        - label: Social Media & Marketing
        - label: Front End Development
        - label: Back End Development
        - label: GitHub & Archiving
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: markdown
    attributes:
      value: "### Please fill in the workstream related information for each of the sections below:"
  - type: textarea
    attributes:
      label: "1. Current Progress"
      id: current-progress
      placeholder: "Enter current progress info. If none, type NONE."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "2. What's Next?"
      id: whats-next
      placeholder: "Enter what's next info. If none, type NONE."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "3. Opportunities, Obstructions, Assistance..."
      id: opp-obs-help
      placeholder: "Enter any opportunities, obstructions or requested help. If none type NONE"
    validations:
      required: true
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    attributes:
      label: "Provide any document links associated with this update."
      id: more-links
      placeholder: "Provide additional links to relevant data here. If there is none, type NONE."
    validations:
      required: true
 
